//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.TotalAndTaxSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TotalAndTaxSvcRef.TotalAndTaxServiceInterface")]
    public interface TotalAndTaxServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTotal", ReplyAction="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTotalResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        float CalculateTotal(object[] prices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTotal", ReplyAction="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTotalResponse")]
        System.Threading.Tasks.Task<float> CalculateTotalAsync(object[] prices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTax", ReplyAction="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTaxResponse")]
        float CalculateTax(float subtotal, float taxRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTax", ReplyAction="http://tempuri.org/TotalAndTaxServiceInterface/CalculateTaxResponse")]
        System.Threading.Tasks.Task<float> CalculateTaxAsync(float subtotal, float taxRate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TotalAndTaxServiceInterfaceChannel : WebApplication.TotalAndTaxSvcRef.TotalAndTaxServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TotalAndTaxServiceInterfaceClient : System.ServiceModel.ClientBase<WebApplication.TotalAndTaxSvcRef.TotalAndTaxServiceInterface>, WebApplication.TotalAndTaxSvcRef.TotalAndTaxServiceInterface {
        
        public TotalAndTaxServiceInterfaceClient() {
        }
        
        public TotalAndTaxServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TotalAndTaxServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TotalAndTaxServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TotalAndTaxServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CalculateTotal(object[] prices) {
            return base.Channel.CalculateTotal(prices);
        }
        
        public System.Threading.Tasks.Task<float> CalculateTotalAsync(object[] prices) {
            return base.Channel.CalculateTotalAsync(prices);
        }
        
        public float CalculateTax(float subtotal, float taxRate) {
            return base.Channel.CalculateTax(subtotal, taxRate);
        }
        
        public System.Threading.Tasks.Task<float> CalculateTaxAsync(float subtotal, float taxRate) {
            return base.Channel.CalculateTaxAsync(subtotal, taxRate);
        }
    }
}
